### ISSUE TITLE
Just qr code tomarket

### ISSUE THREAD

**Issue by lucky2431** [mudachyo/Tomarket#1]
Can't enter from browser, only qr code at page. Script installed..

**Comment by mudachyo** [comment]
Update script and try it again

**Comment by lucky2431** [comment]
Version of script 1.1 but nothing changed. No update anymore and got qr from game.

**Comment by lucky2431** [comment]
> Update script and try it again

Tried, but no change. From webK or webA - can't start game.
![IMG_20240903_132708](https://github.com/user-attachments/assets/b4ab978b-ce0f-4d71-b4aa-dbfc948072fb)

**Comment by mudachyo** [comment]
The problem is not on my side. The problem is on your side. I can't test
scripts for phones
