### ISSUE TITLE
RE ISSUE

### ISSUE THREAD

**Issue by paaavann** [mudachyo/Tomarket#5]
i not testing my scripts in phone

_Originally posted by @mudachyo in https://github.com/mudachyo/Tomarket/issues/4#issuecomment-2362282472_
 
 First of all this is not phone, its a pc
 
 
![image](https://user-images.githubusercontent.com/170100881/369203058-dfabc58c-56cc-4656-bc97-095807341468.png)

**Comment by mudachyo** [comment]
Use a different browser
